name: Build and push Docker images
description: Build and push Docker images with Buildx
author: Kevin Tijssen (TNO)

inputs:
  command: 
    description: 'What do you want to do? (build/push/buildAndPush)'
    required: true
    default: 'build'
  name:
    description: 'Image Name, required'
    required: true
  tags:
    description: 'Image tag, default $GITHUB_SHA'
    required: false
    default: '${GITHUB_SHA}'
  dockerfile:
    description: 'Name of the Dockerfile (Default is ${GITHUB_WORKSPACE}/Dockerfile)'
    required: false
    default: '${GITHUB_WORKSPACE}/Dockerfile'

runs:
  using: "composite"
  steps:
    - name: Docker Build / Push / Build & Push
      shell: bash
      run: |
        echo ${{ inputs.command }}
        echo ${{ inputs.name }}
        echo ${{ inputs.tags }}
        echo ${{ inputs.dockerfile }}
        env