name: Build and push Docker images
description: Build and push Docker images with Buildx
author: Kevin Tijssen (TNO)

inputs:
  command: 
    description: 'What do you want to do? (build/push/buildAndPush)'
    required: true
    default: 'build'
  name:
    description: 'Image Name, required'
    required: true
  tags:
    description: 'Image tag, default $GITHUB_SHA'
    required: false
    default: '$GITHUB_SHA'
  dockerfile:
    description: 'Name of the Dockerfile (Default is $GITHUB_WORKSPACE/Dockerfile)'
    required: false
    default: '$GITHUB_WORKSPACE/Dockerfile'

runs:
  using: "composite"
  steps:
    - name: Docker Build / Push / Build & Push
      shell: bash
      run: |
        
        echo "Checking command"
        if [[ ${{inputs.command}} != @(build|push|buildAndPush) ]]; then
          echo "ERROR: invalid variable '${{ inputs.command }}' for 'command'. Allowed variables are 'build, push, buildAndPush'"
          exit 1
        fi

        echo "Checking name"
        if [[ ! ${{inputs.name}} ]]; then
          echo "ERROR: Missing input for 'name'."
        elif ! [[ ${{inputs.name}} =~ [a-z0-9.-/] ]]; then
          echo "ERROR: invalid name '${{inputs.name}}'. Allow characters are 'a-z0-9./-'"
        fi
        
        echo "The docker command is ${{ inputs.command }}"
        echo "The container name will be ${{ inputs.name }}"
        echo "The following tags will be used ${{ inputs.tags }}"
        echo "The path to the dockerfile is ${{ inputs.dockerfile }}"
        env